version: 0.2
env:
  variables:
     AWS_DEFAULT_REGION: "ap-southeast-1"
     EKS_CLUSTER_NAME: "hlf-lab-eks-sit"
     CIS_ENABLE: "false"

phases:
  build:
    commands:
      - |
        if [ "$CIS_ENABLE" = "true" ]; then
          echo "CIS is enabled, start syncing image..."
          # Install aws-iam-authenticator and kubectl
          curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
          
          # Install kubectl (matching EKS 1.33)
          curl -LO "https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv ./kubectl /usr/local/bin/kubectl
          
          curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

          helm version
          git --version
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
          kubectl get nodes
          
          echo "Container image sync would be performed here if configured"
        else
          echo "CIS is disabled. Skipping image sync."
        fi
      - echo "Container Image Sync step finished."

  post_build:
    commands:
       - echo -e "\nContainer Image Sync step completed"