version: 0.2
env:
  variables:
     AWS_DEFAULT_REGION: "<REDACTED>"
     EKS_CLUSTER_NAME: "<REDACTED>"
phases:
  build:
    commands:
      - |
        if [ "$X_ENABLE" = "true" ]; then
          
          curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
          
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          mv ./kubectl /usr/local/bin/kubectl
          
          curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          
          helm version
          git --version
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
          
          ls -alht
          chmod +x ./script/deploy_plt.sh
          ./script/deploy_plt.sh

        else
          echo "Platform module is disabled. Skipping..."
        fi
      - echo "module deploy step finished!!!"
